### PR TITLE
 Add query root rewrite support 

### PR DESCRIPTION
**Pull request by zoriya**
First basic attempt to support Query Root rewriting to support things like #84.

For now, It only supports rewriting for properties that have a setter (since the data can't be stored after a select otherwise) and a default constructor.

There is no cache support for now.

### CODE REVIEW

**Comment by zoriya** [comment]
After testing a little, this works well when there is a no complex select or other things filters using relations.
For example:
```csharp
DbSet<User>().FirstOrDefault()
```
gets rewritten to:
```csharp
dbContext.Users
          .Select(namelessParameter{0} => new User{ 
              <Id>k__BackingField = namelessParameter{0}.<Id>k__BackingField, 
              <FirstName>k__BackingField = namelessParameter{0}.<FirstName>k__BackingField, 
              <LastName>k__BackingField = namelessParameter{0}.<LastName>k__BackingField, 
              TotalSpent = namelessParameter{0}.Orders
                  .Sum(x => x.Price) 
          }
          )
          .FirstOrDefault()'
```

but something like:

```csharp
dbContext.Users
    .Select(x => new {
        Name = x.FullName,
        x.TotalSpent
    })
	.FirstOrDefault();
```

gets rewritten to:
```csharp
DbSet<User>()
          .Select(namelessParameter{0} => new User{ 
              <Id>k__BackingField = namelessParameter{0}.<Id>k__BackingField, 
              <FirstName>k__BackingField = namelessParameter{0}.<FirstName>k__BackingField, 
              <LastName>k__BackingField = namelessParameter{0}.<LastName>k__BackingField, 
              TotalSpent = namelessParameter{0}.Orders
                  .Sum(x => x.Price) 
          }
          )
          .Select(x => new { 
              Name = x.FullName, 
              TotalSpent = x.Orders
                  .Sum(x => x.Price)
           })
          .FirstOrDefault()'
```
so this fails because the second select references Order which is not loaded by EF.

**Comment by koenbeuk** [comment]
Thanks for taking a swing at this!

> I wonder if there is a way to only rewrite the QueryRootExpression if there is no expression following it.

I think that's exactly what we will want to achieve for the exact problem that you described. I'll see if I can come up with a strategy we can take here.

**Comment by zoriya** [comment]
I like the idea of running a second path for QueryRoot rewriting, but I think it will also need to stop rewriting if the query contains a Select statement, or it will probably make an error. I'm thinking about cases like:
```csharp
int id = await db.Users
    .Select(x => x.Id)
    // This generated select should not be there.
    .Select(namelessParameter{0} => new User{ 
        <Id>k__BackingField = namelessParameter{0}.<Id>k__BackingField, 
        <FirstName>k__BackingField = namelessParameter{0}.<FirstName>k__BackingField, 
        <LastName>k__BackingField = namelessParameter{0}.<LastName>k__BackingField, 
        TotalSpent = namelessParameter{0}.Orders
            .Sum(x => x.Price) 
    })
    .First()
```

**Comment by zoriya** [comment]
The previous cases now work perfectly. The `.Select` is added at the very end of the query, just before a .First()/.ToList() or a the very end when there is no call to those methods. It also handles only the query root or .Sum() and calls where the rewrite should not happen.

I'm going to do more testing in the week to see if I can find cases where it breaks, please comment if you think of one.

**Comment by zoriya** [comment]
Since this PR is way more useful when there is a baking field for a projectable property like:
```csharp
[Projectable(UseMemberBody = nameof(_FullName))]
public string FullName { get; set; }
private string _FullName => FirstName + " " + LastName;

```

I think it would be good to have a way to automatically generate the baking field, allowing to write like below and get the same behavior as above:
```csharp
[Projectable(WithBaking = true)]
public string FullName => FirstName + " " + LastName;
```

I have absolutely no idea how the generator works, so I have not really looked to do that for now.

**Comment by zoriya** [comment]
I tested it on my project, and it works exactly as expected! Since the API for `QueryRootExpression` changed when dotnet7 was released, it needs to have different behaving between the two versions, so I added that on the last commit.

I reused the caching system that already existed for properties, but I did not cache the new Select statement since it would require caching the whole query and I don't think that it's a good tradeoff.

**Pull request merged**
