### PR TITLE
Add support for notnull, struct, class and new() generic constraints

### PR DESCRIPTION
**Pull request by PhenX**

### CODE REVIEW

**Comment by koenbeuk** [comment]
Much appreciated!

**Comment by PhenX** [comment]
Great :) When will it be released on NuGet ?

**Comment by PhenX** [comment]
Oh, I see it failed :( https://github.com/koenbeuk/EntityFrameworkCore.Projectables/actions/runs/6019282267/job/16328879109#step:6:42

**Comment by koenbeuk** [comment]
Done :)

**Pull request merged**
