### PR TITLE
Updated to dotnet 8

### PR DESCRIPTION
**Pull request by koenbeuk**

### CODE REVIEW

**Comment by StonedHackerman** [comment]
Hi,
I tested the .NET 8 branch today and everything works flawlessly, fixing issue #95. All the checks passed, will you merge this branch into main or is there more work to be done?

**Comment by koenbeuk** [comment]
Thanks for testing it out, I have a few uncommitted test cases that were failing which is delaying the release of this version. I've just been swamped and haven't had a chance to get back to this yet. I will try and prioritize this to get this out of the door asap.

**Comment by PhenX** [comment]
Hello @koenbeuk , good thing to update to dotnet 8, but dotnet 6 is not dead yet. Would it be possible to keep it? I know unit tests were changed and will be failing on dotnet 6, but maybe that's not an issue, as you could target only dotnet 8 for them.
We've been waiting for a new release with recent fixes, that would be sad if we could not upgrade our few projects still on dotnet 6 😥
Thank you again!

**Comment by koenbeuk** [comment]
@PhenX dotnet 8 is tied to V4 of this project. V3 can be maintained with dotnet 6 in mind.  I will prep a release for both

**Comment by leoerlandsson** [comment]
Any update here? Is there .NET 8 support?

Can we help in any way?

Thanks!

**Pull request merged**
